---
abstract: 'A Module to create locale objects with localisation data from the CLDR'
author:
  - 'John Imrie <john.imrie1@gmail.com>'
build_requires:
  Test::Exception: '0'
  Test::More: '0.98'
  ok: '0'
configure_requires:
  Module::Build: '0.40'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Locale-CLDR
provides:
  Locale::CLDR:
    file: lib/Locale/CLDR.pm
    version: v0.26.6
  Locale::CLDR::CalendarPreferences:
    file: lib/Locale/CLDR/CalendarPreferences.pm
    version: v0.26.6
  Locale::CLDR::Currencies:
    file: lib/Locale/CLDR/Currencies.pm
    version: v0.26.6
  Locale::CLDR::EraBoundries:
    file: lib/Locale/CLDR/EraBoundries.pm
    version: v0.26.6
  Locale::CLDR::LikelySubtags:
    file: lib/Locale/CLDR/LikelySubtags.pm
    version: v0.26.6
  Locale::CLDR::Locales::En:
    file: lib/Locale/CLDR/Locales/En.pm
    version: v0.26.6
  Locale::CLDR::Locales::En::Any:
    file: lib/Locale/CLDR/Locales/En/Any.pm
    version: v0.26.6
  Locale::CLDR::Locales::En::Any::Us:
    file: lib/Locale/CLDR/Locales/En/Any/Us.pm
    version: v0.26.6
  Locale::CLDR::Locales::Root:
    file: lib/Locale/CLDR/Locales/Root.pm
    version: v0.26.6
  Locale::CLDR::MeasurementSystem:
    file: lib/Locale/CLDR/MeasurementSystem.pm
    version: v0.26.6
  Locale::CLDR::NumberFormatter:
    file: lib/Locale/CLDR/NumberFormatter.pm
    version: v0.26.6
  Locale::CLDR::NumberingSystems:
    file: lib/Locale/CLDR/NumberingSystems.pm
    version: v0.26.6
  Locale::CLDR::Plurals:
    file: lib/Locale/CLDR/Plurals.pm
    version: v0.26.6
  Locale::CLDR::TerritoryContainment:
    file: lib/Locale/CLDR/TerritoryContainment.pm
    version: v0.26.6
  Locale::CLDR::ValidCodes:
    file: lib/Locale/CLDR/ValidCodes.pm
    version: v0.26.6
  Locale::CLDR::WeekData:
    file: lib/Locale/CLDR/WeekData.pm
    version: v0.26.6
requires:
  DateTime: '0.72'
  Moose: '2.0401'
  MooseX::ClassAttribute: '0.26'
  perl: v5.10.0
  version: '0.95'
resources:
  license: http://dev.perl.org/licenses/
version: v0.26.6
